language: node_js
node_js:
- '0.10'
- '0.12'
script:
- npm run lint
notifications:
  email: false
  webhooks:
    secure: efGftuAHShqD1e2pZK1bLQk85U6CcthRKZB3zBs3Zi9PA5V5FgfpNyiqCRaLzFg2fuN5v54/hpUzImSLcEglZR/SZMxDYByREO/OTQLOA82RCGLeMPDimsnGMhq32ODLFZJAatlMRMLu/PFZJg4k9cSGhMsc1R0ohU5F2/GKjoE=
