language: node_js
node_js:
  - '0.10'
  - '0.12'
before_script:
  - npm install -g coffeelint
script:
  - coffeelint scripts external-scripts.json hubot-scripts.json package.json
notifications:
  email: false
  webhooks:
    secure: "q4zYeC78m22WNdaL9FC7Mz6P3AEZJCW7Qzm3MIrMuBZAyGgdoObdF/mPLS51qdAn/fzTbWgE9/MmgU43OjC8XuWGH4pDrfLKfhUBAJZozBNPOeQA07Pxhzm9n7G6UnhyI8/fHuJER3mYCXPMr8kE1wWS/hZPWyEoi+y3s+yB468="
